.g8/stringPage/generated-test/controllers/$className$ControllerSpec.scala
Changing the GET test to be JsString rather then JsNumber
=> Changing invalid value to an empty string in tests

app/forms/Constraints.scala, test/forms/ConstraintsSpec.scala
This will add the ability to validate things against a regex pattern in forms
#52
=> #52 Making a regex constraint

app/controllers/AreYouSelfAssessedController.scala, app/identifiers/AreYouSelfAssessedId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/areYouSelfAssessed.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/AreYouSelfAssessed.sh, test/controllers/AreYouSelfAssessedControllerSpec.scala, test/utils/NavigatorSpec.scala, test/views/AreYouSelfAssessedViewSpec.scala
=> Self assessed page

.g8/questionPage/app/controllers/$className$Controller.scala, .g8/questionPage/app/forms/$className$Form.scala, .g8/questionPage/generated-test/controllers/$className$ControllerSpec.scala, .g8/questionPage/generated-test/forms/$className$FormSpec.scala, .g8/questionPage/generated-test/views/$className$ViewSpec.scala, .g8/questionPage/migrations/$className__snake$.sh, .g8/stringPage/app/controllers/$className$Controller.scala, .g8/stringPage/app/forms/$className$Form.scala, .g8/stringPage/generated-test/controllers/$className$ControllerSpec.scala, .g8/stringPage/generated-test/forms/$className$FormSpec.scala, .g8/stringPage/generated-test/views/$className$ViewSpec.scala, .g8/stringPage/migrations/$className__snake$.sh
Refactoring string page and question page to use constraints and injected app config
#55
=> #55 Updating scaffolds

app/controllers/IsTheAddressInTheUKController.scala, test/controllers/IsTheAddressInTheUKControllerSpec.scala
added custom error for blank response to question on IsTheAddressInTheUk page
#58
=> added custom error on IsTheAddressInTheUk page

.g8/questionPage/app/forms/$className$Form.scala, .g8/questionPage/generated-test/controllers/$className$ControllerSpec.scala, .g8/questionPage/generated-test/forms/$className$FormSpec.scala, .g8/questionPage/generated-test/views/$className$ViewSpec.scala, .g8/stringPage/app/forms/$className$Form.scala, .g8/stringPage/generated-test/forms/$className$FormSpec.scala, .g8/stringPage/generated-test/views/$className$ViewSpec.scala
Fixing a few bugs with the string page and the question page
#55
=> Correcting scaffold bugs

app/controllers/UniqueTaxpayerReferenceController.scala, app/forms/UniqueTaxpayerReferenceForm.scala, app/identifiers/UniqueTaxpayerReferenceId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/uniqueTaxpayerReference.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/UniqueTaxpayerReference.sh, test/controllers/UniqueTaxpayerReferenceControllerSpec.scala, test/forms/UniqueTaxpayerReferenceFormSpec.scala, test/utils/NavigatorSpec.scala, test/views/UniqueTaxpayerReferenceViewSpec.scala
=> create UTR page

app/config/FrontendAppConfig.scala, app/controllers/TelephoneNumberController.scala, app/forms/Constraints.scala, app/forms/TelephoneNumberForm.scala, conf/application.conf, conf/messages.en, test/controllers/TelephoneNumberControllerSpec.scala, test/forms/ConstraintsSpec.scala, test/forms/TelephoneNumberFormSpec.scala, test/views/TelephoneNumberViewSpec.scala
=> Telephone validation

test/utils/NavigatorSpec.scala
Fixing a bug with the UTR route. It was a typo in the test with the wrong Id
=> Fixing UTR route

test/forms/TelephoneNumberFormSpec.scala
Adding the questionForm form behaviour to telephone number to check that a valid string binds
#52
=> Adding the questionForm form behaviour to telephone number to check bind

app/config/FrontendAppConfig.scala, app/forms/UniqueTaxpayerReferenceForm.scala, conf/application.conf, conf/messages.en, test/controllers/UniqueTaxpayerReferenceControllerSpec.scala, test/forms/UniqueTaxpayerReferenceFormSpec.scala, test/views/UniqueTaxpayerReferenceViewSpec.scala
Added regex validation to UTR page
#59
=> added regex validation

app/views/uniqueTaxpayerReference.scala.html, test/views/UniqueTaxpayerReferenceViewSpec.scala
A few sentences describing the overall goals of the pull request's commits.
(Delete if not appropriate)
=> Added UTR hint text

conf/application.conf
Fixing bug in the postcode regex string
#52
=> Updating postcode regex bug

test/utils/CheckYourAnswersHelperSpec.scala
Added the helper spec and tests to improve overall test coverage
#69
=> Addition of check your answers spec

.g8/yesNoPage/generated-test/views/$className$ViewSpec.scala
Update the yesNoPage scaffold view spec to test for backlinks
#93
=> Updated tests for yesNoPage scaffold for backlink

.g8/intPage/generated-test/views/$className$ViewSpec.scala, .g8/intPage/migrations/$className__snake$.sh, .g8/optionsPage/generated-test/views/$className$ViewSpec.scala, .g8/optionsPage/migrations/$className__snake$.sh, .g8/questionPage/generated-test/views/$className$ViewSpec.scala, .g8/yesNoPage/migrations/$className__snake$.sh, test/views/AreYouSelfAssessedViewSpec.scala
Added backlink behaviour to scaffold view specs and updated view specs that were missing backlink test 
#101
=> Refactor scaffold and view specs

app/controllers/SelectTaxYearController.scala, app/forms/SelectTaxYearForm.scala, app/identifiers/SelectTaxYearId.scala, app/models/SelectTaxYear.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/selectTaxYear.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/SelectTaxYear.sh, test/controllers/SelectTaxYearControllerSpec.scala, test/forms/SelectTaxYearFormSpec.scala, test/utils/CheckYourAnswersHelperSpec.scala, test/utils/NavigatorSpec.scala, test/views/SelectTaxYearViewSpec.scala
Added backlink behaviour to scaffold view specs and updated view specs that were missing backlink test 
#90
=> Create select tax year

app/controllers/FullOrPartialClaimController.scala, app/forms/FullOrPartialClaimForm.scala, app/identifiers/FullOrPartialClaimId.scala, app/models/FullOrPartialClaim.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/fullOrPartialClaim.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/FullOrPartialClaim.sh, test/controllers/FullOrPartialClaimControllerSpec.scala, test/forms/FullOrPartialClaimFormSpec.scala, test/utils/NavigatorSpec.scala, test/views/FullOrPartialClaimViewSpec.scala
Did the scaffolding, navigation, validation on blank and content for the Full Partial Claim page
#74
=> Addition of full or partial claim page

app/config/FrontendAppConfig.scala, app/controllers/PartialClaimAmountController.scala, app/forms/PartialClaimAmountForm.scala, app/identifiers/PartialClaimAmountId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/components/input_text.scala.html, app/views/partialClaimAmount.scala.html, conf/app.routes, conf/application.conf, conf/messages.en, migrations/applied_migrations/PartialClaimAmount.sh, test/controllers/PartialClaimAmountControllerSpec.scala, test/forms/PartialClaimAmountFormSpec.scala, test/utils/NavigatorSpec.scala, test/views/PartialClaimAmountViewSpec.scala, test/views/behaviours/StringViewBehaviours.scala
Do the scaffolding, validation on blank and content for the How Much page
Amended stringPage tests to allow prefix
#76
=> created partialClaimAmount page

test/utils/CheckYourAnswersHelperSpec.scala
Update check your answers tests
=> update check your answers tests

.g8/intPage/app/controllers/$className$Controller.scala, .g8/intPage/app/forms/$className$Form.scala, .g8/intPage/generated-test/controllers/$className$ControllerSpec.scala, .g8/intPage/generated-test/forms/$className$FormSpec.scala, .g8/intPage/generated-test/views/$className$ViewSpec.scala, .g8/intPage/migrations/$className__snake$.sh, .g8/questionPage/app/forms/$className$Form.scala, .g8/stringPage/app/forms/$className$Form.scala, app/forms/FullNameForm.scala, app/forms/InternationalAddressForm.scala, app/forms/NationalInsuranceNumberForm.scala, app/forms/PayAsYouEarnForm.scala, app/forms/TelephoneNumberForm.scala, app/forms/UkAddressForm.scala, app/forms/UniqueTaxpayerReferenceForm.scala, app/forms/mappings/Constraints.scala, app/forms/mappings/Formatters.scala, app/forms/mappings/Mappings.scala, test/forms/ConstraintsSpec.scala, test/forms/MappingsSpec.scala
Refactoring on the INT page scaffold
=> Update int page scaffold and downstream mappings from HMRC/scaffolds

app/controllers/AnyBenefitsController.scala, app/controllers/IsTheAddressInTheUKController.scala, app/forms/BooleanForm.scala, test/controllers/AnyBenefitsControllerSpec.scala, test/controllers/IsTheAddressInTheUKControllerSpec.scala, test/forms/BooleanFormSpec.scala, test/views/AnyBenefitsViewSpec.scala, test/views/IsTheAddressInTheUKViewSpec.scala, test/views/behaviours/YesNoViewBehaviours.scala
Refactoring the boolean form to use the new mappings class to be more readable
=> Updating boolean form class to use mappings

.g8/yesNoPage/app/controllers/$className$Controller.scala, .g8/yesNoPage/generated-test/controllers/$className$ControllerSpec.scala, .g8/yesNoPage/generated-test/views/$className$ViewSpec.scala
Updating yesNoPage scaffolds to use the new mapping style boolean form
=> Updating yesNoPage scaffolds to use the new mapping style boolean form

app/controllers/OtherIncomeController.scala, app/identifiers/OtherIncomeId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/otherIncome.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/OtherIncome.sh, test/controllers/OtherIncomeControllerSpec.scala, test/utils/CheckYourAnswersHelperSpec.scala, test/utils/NavigatorSpec.scala, test/views/OtherIncomeViewSpec.scala
Create a yesNo scaffold to ask the user if they have any other taxable income
#94
=> create any other income page and navigator from any benefits

app/controllers/AnyCarBenefitsController.scala, app/identifiers/AnyCarBenefitsId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/UserAnswers.scala, app/views/anyCarBenefits.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/AnyCarBenefits.sh, test/controllers/AnyCarBenefitsControllerSpec.scala, test/views/AnyCarBenefitsViewSpec.scala
Adding a new yesNoPage to ask the user if they had any income from car benefits during the tax year they are claiming for in the PAYE journey
#117
=> creation of any car benefit page

app/controllers/HowMuchCarBenefitsController.scala, app/forms/HowMuchCarBenefitsForm.scala, app/identifiers/HowMuchCarBenefitsId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/UserAnswers.scala, app/views/howMuchCarBenefits.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/HowMuchCarBenefits.sh, test/controllers/HowMuchCarBenefitsControllerSpec.scala, test/forms/HowMuchCarBenefitsFormSpec.scala, test/views/HowMuchCarBenefitsViewSpec.scala
Creating a stringPage to ask the user how much car benefits a user recieves on the tax year they are claiming for. Use Currency Regex
#118
=> initial creation of how much car benefit page

app/controllers/AnyRentalIncomeController.scala, app/identifiers/AnyRentalIncomeId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/UserAnswers.scala, app/views/anyRentalIncome.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/AnyRentalIncome.sh, test/controllers/AnyRentalIncomeControllerSpec.scala, test/views/AnyRentalIncomeViewSpec.scala
Adding a new yesNoPage to ask the user if they had any rental income during the tax year they are claiming for in the PAYE journey
#119
=> creation of any rental income page

app/controllers/HowMuchRentalIncomeController.scala, app/forms/HowMuchRentalIncomeForm.scala, app/identifiers/HowMuchRentalIncomeId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/UserAnswers.scala, app/views/howMuchRentalIncome.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/HowMuchRentalIncome.sh, test/controllers/HowMuchRentalIncomeControllerSpec.scala, test/forms/HowMuchRentalIncomeFormSpec.scala, test/views/HowMuchRentalIncomeViewSpec.scala
Creating a stringPage to ask the user how much rental income a user recieves on the tax year they are claiming for, use currency regex
#120
=> How much rental income

app/controllers/AnyBankBuildingSocietyInterestController.scala, app/identifiers/AnyBankBuildingSocietyInterestId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/UserAnswers.scala, app/views/anyBankBuildingSocietyInterest.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/AnyBankBuildingSocietyInterest.sh, test/controllers/AnyBankBuildingSocietyInterestControllerSpec.scala, test/views/AnyBankBuildingSocietyInterestViewSpec.scala
Adding a new yesNoPage to ask the user if they had any bank or building society interest income during the tax year they are claiming for in the PAYE journey
#121
=> created AnyBankBuildingSocietyInterest page

app/controllers/AnyMedicalBenefitsController.scala, app/identifiers/AnyMedicalBenefitsId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/UserAnswers.scala, app/views/anyMedicalBenefits.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/AnyMedicalBenefits.sh, test/controllers/AnyMedicalBenefitsControllerSpec.scala, test/views/AnyMedicalBenefitsViewSpec.scala
Adding a new yesNoPage to ask the user if they recieved any medical benefits during the tax year they are claiming for in the PAYE journey
#123
=> create any medical benefits page

app/controllers/HowMuchMedicalBenefitsController.scala, app/forms/HowMuchMedicalBenefitsForm.scala, app/identifiers/HowMuchMedicalBenefitsId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/UserAnswers.scala, app/views/howMuchMedicalBenefits.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/HowMuchMedicalBenefits.sh, test/controllers/HowMuchMedicalBenefitsControllerSpec.scala, test/forms/HowMuchMedicalBenefitsFormSpec.scala, test/views/HowMuchMedicalBenefitsViewSpec.scala
Creating a stringPage to ask the user how much medical benefts a user recieves on the tax year they are claiming for
#124
=> create how much medical benefits page

conf/messages.en
Also an amend to address line 1 and 2.
=> Adding content for bank and building society and medical income

app/controllers/AnyOtherTaxableIncomeController.scala, app/identifiers/AnyOtherTaxableIncomeId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/UserAnswers.scala, app/views/anyOtherTaxableIncome.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/AnyOtherTaxableIncome.sh, test/controllers/AnyOtherTaxableIncomeControllerSpec.scala, test/views/AnyOtherTaxableIncomeViewSpec.scala
Adding a new yesNoPage to ask the user if they claimed any other income during the tax year they are claiming for in the PAYE journey
#125
=> create any other taxable income page

app/utils/Navigator.scala, test/utils/NavigatorSpec.scala
Added navigation for benefits section and income section
#112 - #104
=> benefit section and income section navigation

app/controllers/OtherBenefitsDetailsAndAmountController.scala, app/controllers/OtherIncomeDetailsAndAmountController.scala, app/forms/OtherBenefitsDetailsAndAmountForm.scala, app/forms/OtherIncomeDetailsAndAmountForm.scala, app/identifiers/OtherBenefitsDetailsAndAmountId.scala, app/identifiers/OtherIncomeDetailsAndAmountId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/otherBenefitsDetailsAndAmount.scala.html, app/views/otherIncomeDetailsAndAmount.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/OtherBenefitsDetailsAndAmount.sh, migrations/applied_migrations/OtherIncomeDetailsAndAmount.sh, test/controllers/OtherBenefitsDetailsAndAmountControllerSpec.scala, test/controllers/OtherIncomeDetailsAndAmountControllerSpec.scala, test/forms/OtherBenefitsDetailsAndAmountFormSpec.scala, test/forms/OtherIncomeDetailsAndAmountFormSpec.scala, test/utils/NavigatorSpec.scala, test/views/OtherBenefitsDetailsAndAmountViewSpec.scala, test/views/OtherIncomeDetailsAndAmountViewSpec.scala
Added last income and benefit page 
Updated navigator and tests
#112 - #104
=> Income and benefit details pages

conf/messages.en
Content update to messages file.
=> Content updates to income and benefits sections

app/controllers/OtherBenefitsDetailsAndAmountController.scala, app/controllers/OtherIncomeDetailsAndAmountController.scala, app/forms/OtherBenefitsDetailsAndAmountForm.scala, app/forms/OtherIncomeDetailsAndAmountForm.scala, app/identifiers/OtherBenefitsDetailsAndAmountId.scala, app/identifiers/OtherIncomeDetailsAndAmountId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/otherBenefitsDetailsAndAmount.scala.html, app/views/otherIncomeDetailsAndAmount.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/OtherBenefitsDetailsAndAmount.sh, migrations/applied_migrations/OtherIncomeDetailsAndAmount.sh, test/controllers/OtherBenefitsDetailsAndAmountControllerSpec.scala, test/controllers/OtherIncomeDetailsAndAmountControllerSpec.scala, test/forms/OtherBenefitsDetailsAndAmountFormSpec.scala, test/forms/OtherIncomeDetailsAndAmountFormSpec.scala, test/utils/NavigatorSpec.scala, test/views/OtherBenefitsDetailsAndAmountViewSpec.scala, test/views/OtherIncomeDetailsAndAmountViewSpec.scala
A PR for the two other information pages with a larger input field textarea. 
#126  and #112
=> Any other benefits details and any other income details pages 

test/utils/CheckYourAnswersHelperSpec.scala
Updated check your answers tests to improve branch coverage after new pages have been added.
=> updated check your answers tests

app/controllers/WhereToSendPaymentController.scala, app/identifiers/WhereToSendPaymentId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/whereToSendPayment.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/WhereToSendPayment.sh, test/controllers/WhereToSendPaymentControllerSpec.scala, test/utils/CheckYourAnswersHelperSpec.scala, test/utils/NavigatorSpec.scala, test/views/WhereToSendPaymentViewSpec.scala
Created where to send payment page with tests and navigation
=> Created WhereToSendPayment page

app/controllers/PayeeFullNameController.scala, app/forms/PayeeFullNameForm.scala, app/identifiers/PayeeFullNameId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/payeeFullName.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/PayeeFullName.sh, test/controllers/PayeeFullNameControllerSpec.scala, test/forms/PayeeFullNameFormSpec.scala, test/utils/CheckYourAnswersHelperSpec.scala, test/utils/NavigatorSpec.scala, test/views/PayeeFullNameViewSpec.scala
Created new page PayeeFullName
#159
=> Payee name

app/controllers/AgentReferenceNumberController.scala, app/controllers/AnyAgentRefController.scala, app/forms/AgentReferenceNumberForm.scala, app/identifiers/AgentReferenceNumberId.scala, app/identifiers/AnyAgentRefId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/agentReferenceNumber.scala.html, app/views/anyAgentRef.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/AgentReferenceNumber.sh, migrations/applied_migrations/AnyAgentRef.sh, test/controllers/AgentReferenceNumberControllerSpec.scala, test/controllers/AnyAgentRefControllerSpec.scala, test/forms/AgentReferenceNumberFormSpec.scala, test/utils/CheckYourAnswersHelperSpec.scala, test/utils/NavigatorSpec.scala, test/views/AgentReferenceNumberViewSpec.scala, test/views/AnyAgentRefViewSpec.scala
Created Agent Reference Number page
Created Do they have an Agent Ref page
=> Agent ref number and Any agent ref

conf/messages.en
Entering content for payee and agent details into messages file
=> Content for payee details

app/controllers/IsPayeeAddressInTheUKController.scala, app/identifiers/IsPayeeAddressInTheUKId.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/isPayeeAddressInTheUK.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/IsPayeeAddressInTheUK.sh, test/controllers/IsPayeeAddressInTheUKControllerSpec.scala, test/utils/CheckYourAnswersHelperSpec.scala, test/utils/NavigatorSpec.scala, test/views/IsPayeeAddressInTheUKViewSpec.scala
IsPayeeAddressInTheUK created
Statement coverage.: 94.27%
Branch coverage....: 83.33%
=> IsPayeeAddressInTheUK created

app/controllers/WhereToSendPaymentController.scala, app/forms/WhereToSendPaymentForm.scala, app/models/WhereToSendPayment.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/whereToSendPayment.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/WhereToSendPayment.sh, test/controllers/WhereToSendPaymentControllerSpec.scala, test/forms/WhereToSendPaymentFormSpec.scala, test/utils/CheckYourAnswersHelperSpec.scala, test/utils/NavigatorSpec.scala, test/views/WhereToSendPaymentViewSpec.scala
Changing the where to send payment page to an optionPage rather than a yesNoPage.
#173
=> Re-created WhereToSendPaymentPage as an optionPage

app/views/howMuchBankBuildingSocietyInterest.scala.html, app/views/howMuchCarBenefits.scala.html, app/views/howMuchEmploymentAndSupportAllowance.scala.html, app/views/howMuchIncapacityBenefit.scala.html, app/views/howMuchJobseekersAllowance.scala.html, app/views/howMuchMedicalBenefits.scala.html, app/views/howMuchRentalIncome.scala.html, app/views/howMuchStatePension.scala.html, test/views/HowMuchBankBuildingSocietyInterestViewSpec.scala, test/views/HowMuchCarBenefitsViewSpec.scala, test/views/HowMuchEmploymentAndSupportAllowanceViewSpec.scala, test/views/HowMuchIncapacityBenefitViewSpec.scala, test/views/HowMuchJobseekersAllowanceViewSpec.scala, test/views/HowMuchMedicalBenefitsViewSpec.scala, test/views/HowMuchRentalIncomeViewSpec.scala, test/views/HowMuchStatePensionViewSpec.scala
Added missing pound sign to views with amounts and updated tests
#154
=> Added missing pound sign to views and tests

conf/messages.en
Adding payee details content
Adding payee details content
(Delete if not appropriate)
**(Please add labels to the PR's) =============>**
=> payee-details-content-changes

conf/messages.en
Reverts hmrc/claim-tax-refund-frontend#188
=> Revert "payee-details-content-changes"

conf/messages.en
Content for Payee details
Content for Other income
Can we remove the field 1, field 2 and postcode lines? I don't believe they're needed.
(Delete if not appropriate)
**(Please add labels to the PR's) =============>**
=> payee-details-content

app/views/components/input_textarea.scala.html, app/views/otherBenefitsDetailsAndAmount.scala.html, app/views/otherIncomeDetailsAndAmount.scala.html, conf/messages.en, test/views/OtherBenefitsDetailsAndAmountViewSpec.scala, test/views/OtherIncomeDetailsAndAmountViewSpec.scala, test/views/behaviours/ViewBehaviours.scala
Added hint text to OtherBenefitsDetails and OtherIncomeDetails views
=> Added hint text to OtherBenefitsDetails and OtherIncomeDetails

conf/application.conf
Updating the config files to pull in the latest version of ASSETS_FRONTEND
=> Update assets version to 3.0.0

conf/messages.en
Fixed a mistake in content present on the how much medical benefit did you get page
CTR-7
=> [CTR-7] - Fixed content mistake on the medical benefit page

app/forms/PayeeFullNameForm.scala, test/forms/PayeeFullNameFormSpec.scala
updated payee blank error message
CTR-6
=> CTR-6 Update blank error message for payeefullname

app/forms/AgentReferenceNumberForm.scala, test/forms/AgentReferenceNumberFormSpec.scala
=> [CTR-8] - Adding blank message key to agent reference number page

conf/app.routes
Fix to stop loop in the income section
CTR-12
=> Fix looping issue in routes

app/config/FrontendAppConfig.scala, app/forms/AgentReferenceNumberForm.scala, conf/application.conf, conf/messages.en, test/controllers/AgentReferenceNumberControllerSpec.scala, test/forms/AgentReferenceNumberFormSpec.scala
https://jira.tools.tax.service.gov.uk/browse/CTR-53
=> CTR-53 added max length to agent reference

app/config/FrontendAppConfig.scala, app/forms/PayeeFullNameForm.scala, conf/application.conf, conf/messages.en, test/controllers/PayeeFullNameControllerSpec.scala, test/forms/PayeeFullNameFormSpec.scala
https://jira.tools.tax.service.gov.uk/browse/CTR-52
=> Added max length to payee full name

app/controllers/IsTheAddressInTheUKController.scala, conf/application.conf, test/controllers/IsTheAddressInTheUKControllerSpec.scala
Updated redirect to is-address-in-uk
=> Changed redirect to is-address-in-uk

app/config/FrontendAppConfig.scala, app/controllers/IsTheAddressInTheUKController.scala, app/controllers/UserDetailsController.scala, app/controllers/actions/AuthAction.scala, app/controllers/actions/DataRequiredAction.scala, app/controllers/actions/DataRetrievalAction.scala, app/identifiers/UserDetailsId.scala, app/models/UserDetails.scala, app/models/requests/AuthenticatedRequest.scala, app/utils/CheckYourAnswersHelper.scala, app/utils/CheckYourAnswersSection.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/userDetails.scala.html, conf/app.routes, conf/application.conf, conf/messages.en, migrations/applied_migrations/UserDetails.sh, project/FrontendBuild.scala, test/controllers/IsTheAddressInTheUKControllerSpec.scala, test/controllers/UkAddressControllerSpec.scala, test/controllers/UserDetailsControllerSpec.scala, test/controllers/actions/AuthActionSpec.scala, test/controllers/actions/DataRetrievalActionSpec.scala, test/controllers/actions/FakeAuthAction.scala, test/controllers/actions/FakeDataRetrievalAction.scala, test/utils/MockUserAnswers.scala, test/views/UserDetailsViewSpec.scala
Created auth call and UserDetails page
=> Your details auth call

app/views/components/submit_button.scala.html, conf/messages.en
- Updated title after content review.
- Changed all save and continue buttons to just continue.
=> updated title and continue button

app/models/InternationalAddress.scala, app/models/UkAddress.scala, app/utils/CheckYourAnswersHelper.scala, app/viewmodels/AnswerRow.scala, app/views/check_your_answers.scala.html, app/views/components/answer_row.scala.html, app/views/components/answer_section.scala.html, app/views/components/repeater_answer_section.scala.html, app/views/userDetails.scala.html, test/controllers/CheckYourAnswersControllerSpec.scala, test/utils/CheckYourAnswersHelperSpec.scala, test/utils/CheckYourAnswersSectionsSpec.scala, test/utils/MockUserAnswers.scala, test/views/CheckYourAnswersViewSpec.scala, test/views/UserDetailsViewSpec.scala
- Amended address models to have a to asString and format to fix get issues on None for optional lines.
- Added change link flag to answer rows, implementing show and hide on html view, and tests to cover this.
- Added logical iterating id's to html view for CYA.
- Removed back link from user details as its the first page.
- Added contact details to mock user answers to align with telephone number having its own section on CYA.
- Added a CYA view spec, that checks that the correct sections are shown depending on journey chosen. Only tested minimal answers journey this way. 
- Implemented break lines between address lines.
=> updated CYA page and added new tests

conf/application.conf
=> Updated assets frontend version

app/views/components/input_radio.scala.html, conf/application.conf
=> updated frontend version and radio styles

app/utils/CheckYourAnswersHelper.scala, app/utils/CheckYourAnswersSection.scala, conf/messages.en, test/utils/CheckYourAnswersHelperSpec.scala, test/utils/CheckYourAnswersSectionsSpec.scala, test/utils/MockUserAnswers.scala, test/views/CheckYourAnswersViewSpec.scala
Added company details to CYA tests
Refactor link test
=> Refactored non running test files

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, build.sbt, conf/application-json-logger.xml, project/plugins.sbt
DL-1776 
**Enhancement** 
Adding standard auto checklists to repo and setting standardised Logging for frontend having acquired service in Live Services
=> DL-1776 adding checklists and standard logging for LS

app/views/govuk_wrapper.scala.html, build.sbt, project/plugins.sbt
#DL-2045
**Bug fix** (delete as appropriate)
Fixed NoSuchMethodError where user would not even be shown an error page, just blank screen.
=> DL-2045: Removed unnecessary language toggle on error page

app/config/AddressLookupConfig.scala, app/controllers/SessionManagementController.scala, app/views/confirmation.scala.html, app/views/main_template.scala.html, app/views/sessionTimedout.scala.html, app/views/unauthorised.scala.html, conf/app.routes, conf/messages.cy, conf/messages.en
=> DL-2318 - Timeout dialog added

build.sbt
Gov UK Template Updated to pick up welsh skip to content
=> DL-2358 - Gov UK Template Updated to pick up welsh skip to content

app/config/AddressLookupConfig.scala, app/connectors/AddressLookupConnector.scala, build.sbt, test/config/AddressLookupConfigSpec.scala, test/connectors/AddressLookupConnectorSpec.scala
**Bug fix**
Moving to address-lookup api v2 for full Welsh Language support.
=> DL-2334 Moving to address-lookup api v2 for full Welsh Language support.

build.sbt
=> DL-3524 Dependency updates

build.sbt, project/build.properties
=> DL-3739 Updated ReactiveMongo, sbt and bootstrap versions

app/views/govuk_wrapper.scala.html, app/views/main_template.scala.html, app/views/unauthorised_error_template.scala.html, build.sbt, conf/application.conf
=> DL-4231 A11y statement for claim-tax-refund

build.sbt, project/plugins.sbt, project/scaffold.sbt
=> DL-4474 Dependency updates

app/connectors/AddressLookupConnector.scala, app/connectors/CasConnector.scala, app/connectors/CtrConnector.scala, app/controllers/CheckYourAnswersController.scala, app/handlers/ErrorHandler.scala, app/repositories/SessionRepository.scala, app/services/SubmissionService.scala, app/utils/EnumUtils.scala, build.sbt, conf/application.conf, project/plugins.sbt, test/connectors/AddressLookupConnectorSpec.scala, test/forms/AnyAgentReferenceFormSpec.scala, test/forms/BooleanFormSpec.scala, test/forms/FormSpec.scala, test/forms/HowMuchTaxPaidSpec.scala, test/forms/OtherBenefitFormSpec.scala, test/forms/OtherCompanyBenefitFormSpec.scala, test/forms/OtherTaxableIncomeFormSpec.scala, test/forms/TelephoneNumberFormSpec.scala, test/forms/WithRequiredBooleanMappingSpec.scala, test/forms/behaviours/CheckboxBehaviours.scala, test/forms/behaviours/FormBehaviours.scala, test/utils/EnumUtilsSpec.scala
=> DL-5217 - play2.7 upgrade

app/filters/AllowlistFilter.scala, app/filters/FiltersWithAllowlist.scala, build.sbt
=> DL-5333 Change references to whitelist to allowlist

app/config/FrontendAppConfig.scala
=> DL-5474 Contact host config fix

build.sbt, project/plugins.sbt
=> DL-5578 Auth-client upgrade

build.sbt, project/plugins.sbt, test/controllers/AnyCompanyBenefitsControllerSpec.scala, test/controllers/ControllerSpecBase.scala, test/forms/AnyAgentReferenceFormSpec.scala, test/forms/BooleanFormSpec.scala, test/forms/FormSpec.scala, test/forms/HowMuchTaxPaidSpec.scala, test/forms/OtherBenefitFormSpec.scala, test/forms/OtherCompanyBenefitFormSpec.scala, test/forms/OtherTaxableIncomeFormSpec.scala, test/forms/TelephoneNumberFormSpec.scala, test/forms/WithRequiredBooleanMappingSpec.scala, test/forms/behaviours/CheckboxBehaviours.scala, test/forms/behaviours/FormBehaviours.scala, test/models/AnyAgentRefSpec.scala, test/models/AnyTaxPaidSpec.scala, test/models/TelephoneOptionSpec.scala, test/utils/EnumUtilsSpec.scala, test/utils/PaymentDetailsCascadeUpsertSpec.scala, test/utils/TaxableBenefitsCascadeUpsertSpec.scala
=> DL-5793 Play 2.8

app/views/howMuchBereavementAllowance.scala.html, test/controllers/HowMuchBereavementAllowanceControllerSpec.scala, test/views/HowMuchBereavementAllowanceViewSpec.scala, test/views/behaviours/NewStringViewBehaviours.scala
Updated `howMuchBereavementAllowance.scala.html` to new UI
=> DL-5922 howMuchBereavementAllowance.scala.html

app/forms/SelectBenefitsForm.scala, app/models/Benefits.scala, app/views/playComponents/input_check_box.scala.html, app/views/selectBenefits.scala.html, conf/messages, conf/messages.cy, test/controllers/SelectBenefitsControllerSpec.scala, test/views/SelectBenefitsViewSpec.scala, test/views/behaviours/NewCheckboxViewBehaviours.scala
DL-5921
- which-taxable-benefits page
- Play components: input checkbox
=> DL-5921 which-taxable-benefits

app/views/howMuchJobseekersAllowance.scala.html, test/controllers/HowMuchJobseekersAllowanceControllerSpec.scala, test/views/HowMuchJobseekersAllowanceViewSpec.scala
DL-5924
- jobseekers-allowance page
=> DL-5924 jobseekers-allowance

app/views/anyCompanyBenefits.scala.html, test/controllers/AnyCompanyBenefitsControllerSpec.scala, test/views/AnyCompanyBenefitsViewSpec.scala
=> DL-5918 anyCompanyBenefits.scala.html

app/views/howMuchStatePension.scala.html, app/views/playComponents/input_text.scala.html, test/controllers/HowMuchStatePensionControllerSpec.scala, test/views/HowMuchStatePensionViewSpec.scala, test/views/behaviours/NewStringViewBehaviours.scala
Updated `howMuchStatePension.scala.html` to new UI
=> DL-5927 howMuchStatePension.scala.html

app/controllers/HowMuchCarersAllowanceController.scala, app/views/anyBenefits.scala.html, app/views/howMuchCarersAllowance.scala.html, app/views/howMuchStatePension.scala.html, app/views/playComponents/input_text.scala.html, app/views/playComponents/input_yes_no.scala.html, test/controllers/AnyBenefitsControllerSpec.scala, test/controllers/HowMuchCarersAllowanceControllerSpec.scala, test/views/AnyBenefitsViewSpec.scala, test/views/HowMuchCarersAllowanceViewSpec.scala, test/views/behaviours/NewStringViewBehaviours.scala, test/views/behaviours/NewViewBehaviours.scala
=> DL-5923 - carers-allowance

app/controllers/HowMuchEmploymentAndSupportAllowanceController.scala, app/views/howMuchEmploymentAndSupportAllowance.scala.html, test/controllers/HowMuchEmploymentAndSupportAllowanceControllerSpec.scala, test/views/HowMuchEmploymentAndSupportAllowanceViewSpec.scala
=> DL-5925 employment-support-allowance

app/controllers/OtherBenefitController.scala, app/views/otherBenefit.scala.html, app/views/playComponents/input_text.scala.html, test/controllers/OtherBenefitControllerSpec.scala, test/views/OtherBenefitViewSpec.scala, test/views/behaviours/NewQuestionViewBehaviours.scala
=> DL-5930 other-taxable-benefits

app/models/CompanyBenefits.scala, app/views/selectCompanyBenefits.scala.html, conf/messages, conf/messages.cy, test/controllers/SelectCompanyBenefitsControllerSpec.scala, test/views/SelectCompanyBenefitsViewSpec.scala
=> DL-5932 select-company-benefits

app/controllers/AnyOtherBenefitsController.scala, app/views/anyOtherBenefits.scala.html, app/views/playComponents/other_summary.scala.html, test/controllers/AnyOtherBenefitsControllerSpec.scala, test/views/AnyOtherBenefitsViewSpec.scala
=> DL-5931 other-taxable-benefits

app/views/howMuchCarBenefits.scala.html, app/views/howMuchFuelBenefit.scala.html, test/controllers/HowMuchFuelBenefitControllerSpec.scala, test/views/HowMuchFuelBenefitViewSpec.scala
=> DL-5934 - UI migration

app/controllers/ConfirmationController.scala, app/views/confirmation.scala.html, build.sbt, test/controllers/ConfirmationControllerSpec.scala, test/views/ConfirmationViewSpec.scala
Updated howMuchStatePension.scala.html to new UI
=> DL-5978 confirmation.scala.html

app/controllers/TelephoneNumberController.scala, app/views/playComponents/error_summary.scala.html, app/views/playComponents/input_yes_no_with_text_expander.scala.html, app/views/telephoneNumber.scala.html, test/controllers/TelephoneNumberControllerSpec.scala, test/views/TelephoneNumberViewSpec.scala
=> DL-5954 - telephone-number

app/controllers/HowMuchMedicalBenefitsController.scala, app/views/howMuchMedicalBenefits.scala.html, test/controllers/HowMuchMedicalBenefitsControllerSpec.scala, test/views/HowMuchMedicalBenefitsViewSpec.scala
=> DL-5935 medical-benefit play-ui changes.

app/controllers/SelectTaxableIncomeController.scala, app/views/playComponents/input_check_box.scala.html, app/views/selectTaxableIncome.scala.html, test/controllers/SelectTaxableIncomeControllerSpec.scala, test/views/SelectTaxableIncomeViewSpec.scala
Updated `selectTaxableIncome.scala.html` to new UI
=> DL-5939 selectTaxableIncome.scala.html

app/views/anyOtherCompanyBenefits.scala.html, test/controllers/AnyOtherCompanyBenefitsControllerSpec.scala, test/views/AnyOtherCompanyBenefitsViewSpec.scala
=> DL-5937 other-taxable-company-benefits

app/views/howMuchInvestmentOrDividend.scala.html, test/controllers/HowMuchInvestmentOrDividendControllerSpec.scala, test/views/HowMuchInvestmentOrDividendViewSpec.scala
=> DL-5944 investments-dividends

app/views/anyTaxableIncome.scala.html, test/controllers/AnyTaxableIncomeControllerSpec.scala, test/views/AnyTaxableIncomeViewSpec.scala
=> DL-5938 anyTaxableIncome.scala

app/forms/SelectBenefitsForm.scala, app/views/howMuchBankInterest.scala.html, test/controllers/HowMuchBankInterestControllerSpec.scala, test/views/HowMuchBankInterestViewSpec.scala
=> DL-5940 - UI migration

app/controllers/HowMuchForeignIncomeController.scala, app/views/howMuchForeignIncome.scala.html, test/controllers/HowMuchForeignIncomeControllerSpec.scala, test/views/HowMuchForeignIncomeViewSpec.scala
=> DL-5942 HowMuchForeignIncome.scala

app/controllers/AnyTaxableBankInterestController.scala, app/views/anyTaxableBankInterest.scala.html, app/views/playComponents/input_yes_no_with_text_expander.scala.html, test/controllers/AnyTaxableBankInterestControllerSpec.scala, test/views/AnyTaxableBankInterestViewSpec.scala, test/views/NewViewSpecBase.scala, test/views/TelephoneNumberViewSpec.scala
Updated `anyTaxableBankInterest.scala.html` to new UI
=> DL-5941 anyTaxableBankInterest.scala.html update

app/controllers/AnyOtherTaxableIncomeController.scala, app/views/anyOtherTaxableIncome.scala.html, app/views/playComponents/add_list_summary.scala.html, test/controllers/AnyOtherTaxableIncomeControllerSpec.scala, test/views/AnyOtherTaxableIncomeViewSpec.scala
=> DL-5950 did-you-get-any-other-income

app/controllers/HowMuchRentalIncomeController.scala, app/views/howMuchRentalIncome.scala.html, test/controllers/HowMuchRentalIncomeControllerSpec.scala, test/views/HowMuchRentalIncomeViewSpec.scala
=> DL-5946 howMuchRentalIncome.scala

app/controllers/AnyTaxableForeignIncomeController.scala, app/views/anyTaxableForeignIncome.scala.html, test/controllers/AnyTaxableForeignIncomeControllerSpec.scala, test/views/AnyTaxableForeignIncomeViewSpec.scala
=> DL-5943 anyTaxableForeignIncome.scala

app/controllers/AnyTaxableRentalIncomeController.scala, app/views/anyTaxableRentalIncome.scala.html, test/controllers/AnyTaxableRentalIncomeControllerSpec.scala, test/views/AnyTaxableRentalIncomeViewSpec.scala
=> DL-5947 anyTaxableRentalIncome.scala

app/controllers/AnyTaxableInvestmentsController.scala, app/views/anyTaxableInvestments.scala.html, test/controllers/AnyTaxableInvestmentsControllerSpec.scala, test/views/AnyTaxableInvestmentsViewSpec.scala
=> DL-5945 pay-income-tax-investments-dividends

app/controllers/OtherTaxableIncomeController.scala, app/views/otherTaxableIncome.scala.html, test/controllers/OtherTaxableIncomeControllerSpec.scala, test/views/OtherTaxableIncomeViewSpec.scala
=> DL-5948 otherTaxableIncome.scala

app/controllers/WhereToSendPaymentController.scala, app/views/whereToSendPayment.scala.html, test/controllers/WhereToSendPaymentControllerSpec.scala, test/views/WhereToSendPaymentViewSpec.scala
=> DL-5951 whereToSendPayment.scala

app/controllers/NomineeFullNameController.scala, app/views/nomineeFullName.scala.html, test/controllers/NomineeFullNameControllerSpec.scala, test/views/NomineeFullNameViewSpec.scala
=> DL-5952 NomineeFullName.scala

app/controllers/CheckYourAnswersController.scala, app/views/check_your_answers.scala.html, test/controllers/CheckYourAnswersControllerSpec.scala, test/views/CheckYourAnswersViewSpec.scala
Updated check_your_answers.scala.html to new UI
=> DL-5955 check_your_answers.scala.html

app/controllers/AnyAgentRefController.scala, app/views/anyAgentRef.scala.html, test/controllers/AnyAgentRefControllerSpec.scala, test/views/AnyAgentRefViewSpec.scala
=> DL-5953 anyAgentRef.scala

app/controllers/EnterPayeReferenceController.scala, app/views/enterPayeReference.scala.html, test/controllers/EnterPayeReferenceControllerSpec.scala, test/views/EnterPayeReferenceViewSpec.scala
=> DL-6066 enterPayeReference.scala

conf/messages.cy
=> DL-6064 Added missing welsh translation

app/views/unauthorised.scala.html, test/controllers/UnauthorisedControllerSpec.scala, test/views/UnauthorisedViewSpec.scala
=> DL-6070 Unauthorised page

app/views/playComponents/sign_in_button.scala.html, conf/messages, test/views/SessionTimedOutViewSpec.scala
=> DL-6069 signed-out

app/controllers/AnyTaxableOtherIncomeController.scala, app/views/anyTaxableOtherIncome.scala.html, test/controllers/AnyTaxableOtherIncomeControllerSpec.scala, test/views/AnyTaxableOtherIncomeViewSpec.scala
=> DL-5949 anyTaxableOtherIncome.scala

README.md
=> DL-5996 updated README file

app/controllers/DeleteOtherController.scala, app/views/deleteOther.scala.html, test/controllers/DeleteOtherControllerSpec.scala, test/views/DeleteOtherViewSpec.scala
=> DL-6117 deleteOther.scala

app/controllers/EmploymentDetailsController.scala, app/views/anyBenefits.scala.html, app/views/anyCompanyBenefits.scala.html, app/views/anyOtherBenefits.scala.html, app/views/anyOtherCompanyBenefits.scala.html, app/views/anyOtherTaxableIncome.scala.html, app/views/anyTaxableIncome.scala.html, app/views/employmentDetails.scala.html, app/views/paymentAddressCorrect.scala.html, app/views/playComponents/input_yes_no.scala.html, test/controllers/EmploymentDetailsControllerSpec.scala, test/views/EmploymentDetailsViewSpec.scala
Removed InputViewModel in inputYesNo, as it wasn't being used.
=> DL-6118 - employmentDetails

app/controllers/PaymentInternationalAddressController.scala, app/views/deleteOther.scala.html, app/views/paymentInternationalAddress.scala.html, test/controllers/PaymentInternationalAddressControllerSpec.scala, test/views/PaymentInternationalAddressViewSpec.scala
=> DL-6121 paymentInternationalAddress.scala

app/controllers/RemoveOtherSelectedOptionController.scala, app/views/isPaymentAddressInTheUK.scala.html, app/views/removeOtherSelectedOption.scala.html, test/controllers/RemoveOtherSelectedOptionControllerSpec.scala, test/views/RemoveOtherSelectedOptionViewSpec.scala
=> DL-6126 removeOtherSelectedOption.scala

app/views/playComponents/submit_button.scala.html
=> DL-5980 Adding continue button id for journey tests

app/views/anyAgentRef.scala.html, app/views/anyBenefits.scala.html, app/views/anyCompanyBenefits.scala.html, app/views/anyOtherCompanyBenefits.scala.html, app/views/anyOtherTaxableIncome.scala.html, app/views/anyTaxableIncome.scala.html, app/views/anyTaxableInvestments.scala.html, app/views/deleteOther.scala.html, app/views/detailsOfEmploymentOrPension.scala.html, app/views/employmentDetails.scala.html, app/views/enterPayeReference.scala.html, app/views/howMuchBankInterest.scala.html, app/views/howMuchCarBenefits.scala.html, app/views/howMuchForeignIncome.scala.html, app/views/howMuchFuelBenefit.scala.html, app/views/howMuchIncapacityBenefit.scala.html, app/views/howMuchInvestmentOrDividend.scala.html, app/views/howMuchStatePension.scala.html, app/views/isPaymentAddressInTheUK.scala.html, app/views/nomineeFullName.scala.html, app/views/otherBenefit.scala.html, app/views/otherCompanyBenefit.scala.html, app/views/otherTaxableIncome.scala.html, app/views/paymentUKAddress.scala.html, test/base/SpecBase.scala
=> DL-6149 Clearing up compilation warnings

app/views/removeOtherSelectedOption.scala.html
=> DL-6150 fixed format differences

app/utils/CheckYourAnswersHelper.scala, app/views/confirmation.scala.html, app/views/telephoneNumber.scala.html, conf/messages, conf/messages.cy, test/utils/CheckYourAnswersHelperSpec.scala, test/views/behaviours/NewCheckboxViewBehaviours.scala
=>  DL-6211 content and layout modified

app/views/check_your_answers.scala.html, app/views/error_template.scala.html, app/views/sessionTimedout.scala.html, app/views/unauthorised.scala.html
=> DL-6371 remove back/signout links

app/config/AddressLookupConfig.scala
=> DL-7784 - Amended signout URL

app/views/Layout.scala.html
=> DL-11952 Convert layout to use hmrcStandardPage

app/models/Date.scala, app/models/OtherBenefit.scala, app/models/OtherCompanyBenefit.scala, app/models/OtherTaxableIncome.scala, app/models/SubmissionResponse.scala, app/models/UserDetails.scala, app/repositories/SessionRepository.scala, app/views/LayoutProvider.scala, app/views/playComponents/AdditionalScript.scala.html, build.sbt, conf/application.conf, conf/prod.routes, project/AppDependencies.scala, project/plugins.sbt
=> DL-12320 Updating dependencies

project/AppDependencies.scala
=> DL-12982 update crown logo

app/repositories/SessionRepository.scala
=> DL-14111 Correcting format for Mongo TTL

app/repositories/SessionRepository.scala
=> DL-14111 Removing logic to update old answers
